apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
      annotations:
        prometheus.io/scrape: "true"        # Enable scraping
        prometheus.io/path: "/actuator/prometheus"  # Metrics endpoint path
        prometheus.io/port: "8080"    
    spec:
      containers:
      - name: spring-boot-app
        image: tushar8117/ultimate-cicd:4
        ports:
        - containerPort: 8080
